#!/system/bin/sh

#############################################
#             Kernel & VM Tweaks            #
#############################################

# Disable logger - Performance boost & save memory

rm /dev/log/main

#############################################

sysctl -w kernel.panic_on_oops=1;
sysctl -w kernel.panic=15;
sysctl -w fs.lease-break-time=10;
sysctl -w vm.swappiness=20;
sysctl -w vm.dirty_ratio=90;
sysctl -w vm.dirty_background_ratio=55;
sysctl -w vm.vfs_cache_pressure=20;
sysctl -w vm.min_free_kbytes=11200;
sysctl -w vm.overcommit_memory=1;

echo 0,1,2,4,9,15 > /sys/module/lowmemorykiller/parameters/adj;

echo 3046,4172,6400,8960,15360,25600 > /sys/module/lowmemorykiller/parameters/minfree;

# 3046,4172,5299,7347,8473,9692 Stock

#############################################
#                  mount's                  #
#############################################

busybox mount -o remount,noatime,barrier=0,nobh /system
busybox mount -o remount,noatime,barrier=0,nobh /data
busybox mount -o remount,noatime,barrier=0,nobh /cache

#############################################
#                    Wipe                   #
#############################################

rm -r /cache/*.apk
rm -r /cache/*.tmp
rm -r /data/dalvik-cache/*.apk
rm -r /data/dalvik-cache/*.tmp
rm -r /data/local/*.apk
rm -r /data/local/*.tmp

#############################################
#                I/O scheduler              #
#############################################

echo "sio" > /sys/block/mmcblk0/queue/scheduler;
echo "0" > /sys/block/mmcblk0/queue/iostats;

#############################################
#                    CPU                    #       
#############################################

echo "smartassV2" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;

echo "1401600" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq;

echo "134400" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq;

#############################################
#                 read_ahead                #
#############################################

echo 256 > /sys/devices/virtual/bdi/179:0/read_ahead_kb;

#############################################
#                  zipalign                 #
#############################################

LOG_FILE=/data/zipalign.log;
ZIPALIGNDB=/data/zipalign.db;

if [ -e $LOG_FILE ]; then
	rm $LOG_FILE;
fi;

if [ ! -f $ZIPALIGNDB ]; then
	touch $ZIPALIGNDB;
fi;

echo "Starting FV Automatic ZipAlign $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE;

for DIR in /system/app /data/app; do
	cd $DIR;
	for APK in *.apk; do
		if [ $APK -ot $ZIPALIGNDB ] && [ $(grep "$DIR/$APK" $ZIPALIGNDB|wc -l) -gt 0 ]; then
			echo "Already checked: $DIR/$APK" | tee -a $LOG_FILE;
		else
			ZIPCHECK=`/system/xbin/zipalign -c -v 4 $APK | grep FAILED | wc -l`;
			if [ $ZIPCHECK == "1" ]; then
				echo "Now aligning: $DIR/$APK" | tee -a $LOG_FILE;
				/system/xbin/zipalign -v -f 4 $APK /data/local/$APK;
				busybox mount -o rw,remount /system;
				cp -f -p /data/local/$APK $APK;
				grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB;
			else
				echo "Already aligned: $DIR/$APK" | tee -a $LOG_FILE;
				grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB;
			fi;
		fi;
	done;
done;

busybox mount -o ro,remount /system;
touch $ZIPALIGNDB;
echo "Automatic ZipAlign finished at $( date +"%m-%d-%Y %H:%M:%S" )" | tee -a $LOG_FILE;

# Thanks Gustavo! :P

